src/AspNetCoreAuth2/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspNetCoreAuth2.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

src/AspNetCoreAuth2/Pages/Account/Login.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

namespace AspNetCoreAuth2.Pages.Account
{
    public class LoginModel : PageModel
    {
        [BindProperty]
        public LoginInputModel LoginInputModel {get;set;}

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (!IsUserAuthenticated(LoginInputModel.UserName, LoginInputModel.Password))
            {
                ModelState.AddModelError(string.Empty, "Usúario ou senha inválidos");
                return Page();
            }

            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, LoginInputModel.UserName)
            };

            var userIdentity = new ClaimsIdentity(claims, "login");
            var principal = new ClaimsPrincipal(userIdentity);

            await HttpContext.SignInAsync(principal);
            return Redirect("/");
        }

        public async Task<IActionResult> OnPostLogout()
        {
            await HttpContext.SignOutAsync();
            return Redirect("/");
        }

        private bool IsUserAuthenticated(string userName, string password)
        {
            //simulação de autenticação no banco de dados.
            return true;
        }
    }
}

src/AspNetCoreAuth2/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspNetCoreAuth2.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

src/AspNetCoreAuth2/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspNetCoreAuth2.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/AspNetCoreAuth2/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspNetCoreAuth2.Pages
{
    [Authorize]
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

src/AspNetCoreAuth2/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

src/AspNetCoreAuth2/Pages/Account/Login.cshtml
@page
@model AspNetCoreAuth2.Pages.Account.LoginModel
@{
    ViewData["Title"] = "Login";
}

<section class="hero is-primary is-fullheight">
    <div class="hero-body">
        <div class="container has-text-centered">
            <h1 class="title pacifico larger-text">
                AspNet Core Auth
            </h1>
            <div class="columns">
                <div class="column is-half is-offset-one-quarter">

                    <form method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="field">
                            <p class="control has-icons-left ">
                                <input asp-for="LoginInputModel.UserName" class="input is-large" name="username" placeholder="Username">
                                <span class="icon is-small is-left">
                                    <i class="fas fa-user"></i>
                                </span>
                                <span asp-validation-for="LoginInputModel.UserName" class="is-danger"></span>
                            </p>
                            </div>
                            <div class="field">
                                <p class="control has-icons-left">
                                    <input asp-for="LoginInputModel.Password" class="input is-large" name="password" type="password" placeholder="password">
                                    <span class="icon is-small is-left">
                                        <i class="fas fa-lock"></i>
                                    </span>
                                    <span asp-validation-for="LoginInputModel.Password" class="is-danger"></span>
                                </p>
                            </div>
                            <p>
                                <button class="button is-primary is-inverted is-outlined is-large is-fullwidth">LOGIN</button>
                                <br>
                            </p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

src/AspNetCoreAuth2/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/AspNetCoreAuth2/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<section class="hero is-primary is-fullheight">
    <div class="hero-body">
        <div class="container has-text-centered">
            <h2 class="title larger-text">
                ASP.NET Core Auth2.0
            </h2>
            <h1 class="larger-text">
                @User.Identity.Name
            </h1>
            <h2 class="subtitle">
                You are authenticated!
            </h2>
            <form method="post">
                <p>
                    <button class="button is-primary is-inverted is-outlined is-large is-fullwidth" asp-page="/Account/Login" asp-page-handler="Logout">LOGOFF</button>
                    <br>
                </p>
            </form>
            
        </div>
    </div>
</section>

src/AspNetCoreAuth2/Pages/_Layout.cshtml
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <title>ASP.NET Core Auth2.0</title>
    <base href="/">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="favicon.ico">
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bulma-0.6.2/css/bulma.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/lib/font-awesome/font-awesome.min.css" rel="stylesheet" />
    </environment>

    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css"
              asp-fallback-href="~/lib/bulma-0.6.2/css/bulma.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
              asp-fallback-href="~/lib/font-awesome/font-awesome.min.css"
              asp-append-version="true" />

        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    
    @RenderSection("css", required: false)
</head>

<body>
    @RenderBody()
    <script src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/font-awesome/all.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"
                asp-fallback-src="~/lib/font-awesome/all.js">
        </script>

        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>

        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>

</html>

src/AspNetCoreAuth2/Pages/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetCoreAuth2</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">AspNetCoreAuth2</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/About">About</a></li>
                    <li><a asp-page="/Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - AspNetCoreAuth2</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>